package accountconnect

import "errors"

var (
	ErrInvalidPrincipal     = errors.New("accountconnect: principal is required")
	ErrInvalidClientName    = errors.New("accountconnect: client name is required")
	ErrInvalidRedirect      = errors.New("accountconnect: redirect URL mismatch")
	ErrInvalidState         = errors.New("accountconnect: invalid OAuth state")
	ErrInvalidPKCE          = errors.New("accountconnect: PKCE verification failed")
	ErrSessionExpired       = errors.New("accountconnect: OAuth session expired")
	ErrMissingCode          = errors.New("accountconnect: missing authorization code")
	ErrProviderDenied       = errors.New("accountconnect: Google authorization denied")
	ErrMissingRefresh       = errors.New("accountconnect: missing refresh token")
	ErrUnverifiedIdentity   = errors.New("accountconnect: Google subject and email are required")
	ErrSubjectMismatch      = errors.New("accountconnect: Google subject does not match the connection")
	ErrUnknownAccount       = errors.New("accountconnect: unknown account")
	ErrForbiddenAccount     = errors.New("accountconnect: account is not owned by this principal")
	ErrAccountOwned         = errors.New("accountconnect: Google account is already connected")
	ErrInvalidAuthMode      = errors.New("accountconnect: unsupported auth mode")
	ErrMissingScopes        = errors.New("accountconnect: scopes are required")
	ErrMissingGrantedScopes = errors.New("accountconnect: provider did not report granted scopes")
	ErrNilRegistry          = errors.New("accountconnect: registry is required")
	ErrNilTokens            = errors.New("accountconnect: token store is required")
	ErrNilOAuth             = errors.New("accountconnect: OAuth provider is required")
	ErrNilController        = errors.New("accountconnect: controller is required")
	ErrIncompleteAuth       = errors.New("accountconnect: incomplete auth URL params")
	ErrEmptyRegistryPath    = errors.New("accountconnect: empty registry path")
	ErrRevokeFailed         = errors.New("accountconnect: Google revoke failed")
	ErrInvalidHost          = errors.New("accountconnect: request host is not allowed")
	ErrInvalidOrigin        = errors.New("accountconnect: request origin is not allowed")
)
