// Package mailcompose builds deterministic, bounded RFC 2822 MIME messages
// from structured input. It performs no I/O and does not decide whether the
// caller is authorized to use a sending identity.
package mailcompose

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"mime"
	"mime/quotedprintable"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"golang.org/x/net/html"
)

// ContentFormat selects the representations supplied by the caller.
type ContentFormat string

const (
	// FormatPlain emits a text/plain message.
	FormatPlain ContentFormat = "plain"
	// FormatHTML emits a text/html message.
	FormatHTML ContentFormat = "html"
	// FormatPlainWithHTML emits a plain part and an HTML part generated by
	// escaping paragraphs and line breaks from Plain. Markdown is not parsed.
	FormatPlainWithHTML ContentFormat = "plain_with_html_alternative"
	// FormatPlainAndHTML emits caller-supplied text/plain and text/html parts.
	FormatPlainAndHTML ContentFormat = "plain_and_html_alternative"
)

const (
	maxSubjectBytes        = 255
	maxAddressBytes        = 1024
	maxThreadIDLength      = 256
	maxMessageIDComponents = 50
	maxFilenameBytes       = 255
	maxContentTypeBytes    = 255
	maxHeaderLineBytes     = 998
	base64LineWidth        = 76
	maxBoundaryBytes       = 30
	maxMIMEOverheadBytes   = 4096
	maxPreviewBytes        = 64 << 10
)

// Limits constrain resource use. A nil Limits uses DefaultLimits. Callers may
// lower a limit, but cannot exceed its package default.
type Limits struct {
	MaxRecipientsPerField int
	MaxReferences         int
	MaxAttachments        int
	MaxBodyBytes          int
	MaxAttachmentBytes    int
	MaxMessageBytes       int
}

// DefaultLimits returns the package's fixed upper bounds.
func DefaultLimits() Limits {
	return Limits{
		MaxRecipientsPerField: 100,
		MaxReferences:         50,
		MaxAttachments:        25,
		MaxBodyBytes:          2 << 20,
		MaxAttachmentBytes:    20 << 20,
		MaxMessageBytes:       20 << 20,
	}
}

// Content contains explicitly formatted message text.
type Content struct {
	Format ContentFormat
	Plain  string
	HTML   string
}

// Signature contains the exact content supplied by the controller. The package
// never fetches or invents a Gmail signature.
type Signature struct {
	Plain string
	HTML  string
}

// Reply contains RFC threading headers and Gmail's opaque API thread ID.
type Reply struct {
	InReplyTo  string
	References []string
	ThreadID   string
}

// Attachment contains already-loaded bytes. The package never reads paths.
type Attachment struct {
	Filename    string
	ContentType string
	Data        []byte
}

// Input is the complete composition request. From must already be a verified
// sending identity in the controller's trust model.
type Input struct {
	From             string
	To               []string
	Cc               []string
	Bcc              []string
	Subject          string
	Content          Content
	Signature        Signature
	IncludeSignature bool
	Reply            Reply
	Date             time.Time
	Attachments      []Attachment
	Limits           *Limits
}

// Address is a normalized RFC 5322 address.
type Address struct {
	Name  string `json:"name,omitempty"`
	Email string `json:"email"`
}

// ReplySummary separates SMTP-visible threading headers from the Gmail API
// thread ID, which must be supplied separately in the Message resource.
type ReplySummary struct {
	InReplyTo  string   `json:"in_reply_to,omitempty"`
	References []string `json:"references,omitempty"`
	ThreadID   string   `json:"thread_id,omitempty"`
}

// AttachmentSummary describes an attachment without exposing its bytes.
type AttachmentSummary struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Size        int    `json:"size"`
}

// ContentPreview contains rendered body text, bounded for review. It is the
// exact MIME content up to the UTF-8-safe truncation boundary.
type ContentPreview struct {
	Plain          string `json:"plain"`
	HTML           string `json:"html,omitempty"`
	PlainTruncated bool   `json:"plain_truncated,omitempty"`
	HTMLTruncated  bool   `json:"html_truncated,omitempty"`
}

// Summary is safe for caller review. Bcc is included because the caller chose
// those recipients; Gmail's send API also uses the RFC Bcc header.
type Summary struct {
	From              Address             `json:"from"`
	To                []Address           `json:"to"`
	Cc                []Address           `json:"cc,omitempty"`
	Bcc               []Address           `json:"bcc,omitempty"`
	Subject           string              `json:"subject"`
	Format            ContentFormat       `json:"format"`
	Date              time.Time           `json:"date"`
	MessageID         string              `json:"message_id"`
	Reply             ReplySummary        `json:"reply,omitempty"`
	SignatureIncluded bool                `json:"signature_included"`
	Attachments       []AttachmentSummary `json:"attachments,omitempty"`
	RawSize           int                 `json:"raw_size"`
	Base64URLSize     int                 `json:"base64url_size"`
	Preview           ContentPreview      `json:"preview"`
	Warnings          []string            `json:"warnings,omitempty"`
}

// Result is ready for Gmail Message.Raw after base64url encoding.
type Result struct {
	Raw       []byte
	Base64URL string
	Summary   Summary
}

// ValidationError reports invalid composition input.
type ValidationError struct {
	Message string
}

func (err ValidationError) Error() string {
	return err.Message
}

func validationError(format string, args ...any) ValidationError {
	return ValidationError{Message: fmt.Sprintf(format, args...)}
}

var (
	threadIDPattern  = regexp.MustCompile(`^[A-Za-z0-9_.-]{1,256}$`)
	messageIDPattern = regexp.MustCompile(`^<[^<>\r\n\t ]+@[^<>\r\n\t ]+>$`)
)

// Compose validates input and renders MIME bytes without sending them.
func Compose(in Input) (Result, error) {
	limits, err := effectiveLimits(in.Limits)
	if err != nil {
		return Result{}, err
	}

	if in.Date.IsZero() {
		return Result{}, validationError("date is required for deterministic output")
	}
	date := in.Date.UTC()

	from, err := parseAddress(in.From, "From")
	if err != nil {
		return Result{}, err
	}

	to, cc, bcc, err := parseRecipientGroups(in, limits.MaxRecipientsPerField)
	if err != nil {
		return Result{}, err
	}

	subject, err := validateSubject(in.Subject)
	if err != nil {
		return Result{}, err
	}

	reply, err := validateReply(in.Reply, limits.MaxReferences)
	if err != nil {
		return Result{}, err
	}

	normalized, err := normalizeContent(in.Content)
	if err != nil {
		return Result{}, err
	}

	signature, err := normalizeSignature(in, normalized.Format)
	if err != nil {
		return Result{}, err
	}

	sourceSize := len(normalized.Plain) + len(normalized.HTML) + len(signature.Plain) + len(signature.HTML)
	if sourceSize > limits.MaxBodyBytes {
		return Result{}, validationError("body is %d bytes, limit is %d", sourceSize, limits.MaxBodyBytes)
	}

	plain, htmlText, warnings, err := renderContent(normalized, signature, in.IncludeSignature)
	if err != nil {
		return Result{}, err
	}

	if (normalized.Format == FormatHTML || normalized.Format == FormatPlainAndHTML) && strings.TrimSpace(htmlText) == "" {
		return Result{}, validationError("HTML contains no permitted content")
	}

	if bodySize := len(plain) + len(htmlText); bodySize > limits.MaxBodyBytes {
		return Result{}, validationError("body is %d bytes, limit is %d", bodySize, limits.MaxBodyBytes)
	}

	attachments, err := validateAttachments(in.Attachments, limits)
	if err != nil {
		return Result{}, err
	}

	attachmentSummaries := make([]AttachmentSummary, 0, len(attachments))
	for _, attachment := range attachments {
		attachmentSummaries = append(attachmentSummaries, attachment.summary)
	}

	messageID := generatedMessageID(date, from, to, cc, bcc, subject, normalized, signature, reply, attachments)

	raw, err := renderMIME(messageID, date, from, to, cc, bcc, subject, reply, normalized.Format, plain, htmlText, attachments)
	if err != nil {
		return Result{}, err
	}

	if len(raw) > limits.MaxMessageBytes {
		return Result{}, validationError("message is %d bytes, limit is %d", len(raw), limits.MaxMessageBytes)
	}
	encoded := base64.RawURLEncoding.EncodeToString(raw)

	return Result{
		Raw:       raw,
		Base64URL: encoded,
		Summary: Summary{
			From: from, To: to, Cc: cc, Bcc: bcc,
			Subject: subject, Format: normalized.Format, Date: date,
			MessageID:         messageID,
			Reply:             reply,
			SignatureIncluded: in.IncludeSignature,
			Attachments:       attachmentSummaries,
			RawSize:           len(raw), Base64URLSize: len(encoded),
			Preview:  boundedPreview(plain, htmlText),
			Warnings: warnings,
		},
	}, nil
}

func effectiveLimits(limits *Limits) (Limits, error) {
	defaults := DefaultLimits()
	if limits == nil {
		return defaults, nil
	}
	got := *limits

	fields := []struct {
		name  string
		value *int
		limit int
	}{
		{"MaxRecipientsPerField", &got.MaxRecipientsPerField, defaults.MaxRecipientsPerField},
		{"MaxReferences", &got.MaxReferences, defaults.MaxReferences},
		{"MaxAttachments", &got.MaxAttachments, defaults.MaxAttachments},
		{"MaxBodyBytes", &got.MaxBodyBytes, defaults.MaxBodyBytes},
		{"MaxAttachmentBytes", &got.MaxAttachmentBytes, defaults.MaxAttachmentBytes},
		{"MaxMessageBytes", &got.MaxMessageBytes, defaults.MaxMessageBytes},
	}

	for _, field := range fields {
		if *field.value <= 0 {
			*field.value = field.limit
		}

		if *field.value > field.limit {
			return Limits{}, validationError("%s is %d, package limit is %d", field.name, *field.value, field.limit)
		}
	}

	return got, nil
}

func parseAddress(value, field string) (Address, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return Address{}, validationError("%s is required", field)
	}

	if err := rejectHeaderValue(trimmed, field); err != nil {
		return Address{}, err
	}

	parsed, err := mail.ParseAddress(trimmed)
	if err != nil || parsed == nil || strings.TrimSpace(parsed.Address) == "" {
		return Address{}, validationError("invalid %s address", field)
	}

	if len(trimmed) > maxAddressBytes {
		return Address{}, validationError("%s is %d bytes, limit is %d", field, len(trimmed), maxAddressBytes)
	}
	parsed.Address = normalizeEmailDomain(parsed.Address)

	return Address{Name: parsed.Name, Email: parsed.Address}, nil
}

func normalizeEmailDomain(value string) string {
	at := strings.LastIndex(value, "@")
	if at < 0 {
		return value
	}

	return value[:at] + strings.ToLower(value[at:])
}

func parseRecipientGroups(in Input, maxPerField int) (to, cc, bcc []Address, err error) {
	seen := make(map[string]struct{})

	to, err = parseRecipients(in.To, "To", maxPerField, seen)
	if err != nil {
		return nil, nil, nil, err
	}

	if len(to) == 0 {
		return nil, nil, nil, validationError("To is required")
	}

	cc, err = parseRecipients(in.Cc, "Cc", maxPerField, seen)
	if err != nil {
		return nil, nil, nil, err
	}

	bcc, err = parseRecipients(in.Bcc, "Bcc", maxPerField, seen)
	if err != nil {
		return nil, nil, nil, err
	}

	return to, cc, bcc, nil
}

func parseRecipients(values []string, field string, limit int, seen map[string]struct{}) ([]Address, error) {
	if len(values) > limit {
		return nil, validationError("%s has %d addresses, limit is %d", field, len(values), limit)
	}

	out := make([]Address, 0, len(values))
	for _, value := range values {
		address, err := parseAddress(value, field)
		if err != nil {
			return nil, err
		}

		key := strings.ToLower(address.Email)
		if _, exists := seen[key]; exists {
			return nil, validationError("duplicate recipient %s", address.Email)
		}
		seen[key] = struct{}{}

		out = append(out, address)
	}

	return out, nil
}

func validateSubject(value string) (string, error) {
	subject := strings.TrimSpace(value)
	if subject == "" {
		return "", validationError("subject is required")
	}

	if err := rejectHeaderValue(subject, "subject"); err != nil {
		return "", err
	}

	if len(subject) > maxSubjectBytes {
		return "", validationError("subject is %d bytes, limit is %d", len(subject), maxSubjectBytes)
	}

	return subject, nil
}

func validateReply(reply Reply, maxReferences int) (ReplySummary, error) {
	summary := ReplySummary{ThreadID: strings.TrimSpace(reply.ThreadID)}
	if reply.InReplyTo = strings.TrimSpace(reply.InReplyTo); reply.InReplyTo != "" {
		if err := rejectHeaderValue(reply.InReplyTo, "In-Reply-To"); err != nil {
			return ReplySummary{}, err
		}

		if !messageIDPattern.MatchString(reply.InReplyTo) {
			return ReplySummary{}, validationError("In-Reply-To must contain one RFC 5322 Message-ID")
		}
		summary.InReplyTo = reply.InReplyTo
	}

	if len(reply.References) > maxReferences {
		return ReplySummary{}, validationError("References has %d IDs, limit is %d", len(reply.References), maxReferences)
	}

	for _, reference := range reply.References {
		reference = strings.TrimSpace(reference)
		if reference == "" {
			return ReplySummary{}, validationError("References contains an empty Message-ID")
		}

		if err := rejectHeaderValue(reference, "References"); err != nil {
			return ReplySummary{}, err
		}

		if !messageIDPattern.MatchString(reference) {
			return ReplySummary{}, validationError("each References entry must contain one RFC 5322 Message-ID")
		}
		summary.References = append(summary.References, reference)
	}

	if summary.ThreadID != "" && len(summary.ThreadID) > maxThreadIDLength {
		return ReplySummary{}, validationError("thread ID is %d bytes, limit is %d", len(summary.ThreadID), maxThreadIDLength)
	}

	if summary.ThreadID != "" && !threadIDPattern.MatchString(summary.ThreadID) {
		return ReplySummary{}, validationError("thread ID contains invalid characters")
	}

	return summary, nil
}

func normalizeContent(content Content) (Content, error) {
	format := ContentFormat(strings.TrimSpace(string(content.Format)))
	plain := normalizeCRLF(content.Plain)
	htmlText := normalizeCRLF(content.HTML)

	if format == "markdown" {
		return Content{}, validationError(`content format "markdown" is unsupported; provide plain, html, plain_with_html_alternative, or plain_and_html_alternative`)
	}

	switch format {
	case FormatPlain:
		if err := requireContent(plain, "plain"); err != nil {
			return Content{}, err
		}

		if strings.TrimSpace(htmlText) != "" {
			return Content{}, validationError("HTML must be empty for plain format")
		}
	case FormatHTML:
		if err := requireContent(htmlText, "HTML"); err != nil {
			return Content{}, err
		}
	case FormatPlainWithHTML:
		if err := requireContent(plain, "plain"); err != nil {
			return Content{}, err
		}

		if strings.TrimSpace(htmlText) != "" {
			return Content{}, validationError("HTML must be empty for plain_with_html_alternative format")
		}
	case FormatPlainAndHTML:
		if err := requireContent(plain, "plain"); err != nil {
			return Content{}, err
		}

		if err := requireContent(htmlText, "HTML"); err != nil {
			return Content{}, err
		}
	default:
		return Content{}, validationError("unsupported content format %q", format)
	}

	return Content{Format: format, Plain: plain, HTML: htmlText}, nil
}

func normalizeSignature(in Input, format ContentFormat) (Signature, error) {
	signature := Signature{
		Plain: normalizeCRLF(in.Signature.Plain),
		HTML:  normalizeCRLF(in.Signature.HTML),
	}
	if !in.IncludeSignature {
		return Signature{}, nil
	}

	switch format {
	case FormatPlain:
		if strings.TrimSpace(signature.Plain) == "" {
			return Signature{}, validationError("plain signature is required")
		}
	case FormatHTML:
		if strings.TrimSpace(signature.HTML) == "" {
			return Signature{}, validationError("HTML signature is required")
		}

		if strings.TrimSpace(in.Content.Plain) != "" && strings.TrimSpace(signature.Plain) == "" {
			return Signature{}, validationError("plain signature is required when a plain body is supplied")
		}
	case FormatPlainWithHTML:
		if strings.TrimSpace(signature.Plain) == "" {
			return Signature{}, validationError("plain signature is required")
		}
	case FormatPlainAndHTML:
		if strings.TrimSpace(signature.Plain) == "" || strings.TrimSpace(signature.HTML) == "" {
			return Signature{}, validationError("plain and HTML signatures are required")
		}
	}

	return signature, nil
}

func renderContent(content Content, signature Signature, include bool) (plain, htmlText string, warnings []string, err error) {
	plain = content.Plain
	switch content.Format {
	case FormatPlainWithHTML:
		htmlText = plainToHTML(content.Plain)
	case FormatHTML:
		htmlText, warnings, err = sanitizeHTML(content.HTML)
		if err != nil {
			return "", "", nil, err
		}

		plain = content.Plain
		if strings.TrimSpace(plain) == "" {
			plain = htmlToText(htmlText)
		}
	case FormatPlainAndHTML:
		htmlText, warnings, err = sanitizeHTML(content.HTML)
		if err != nil {
			return "", "", nil, err
		}
		plain = content.Plain
	}

	if !include {
		return plain, htmlText, warnings, nil
	}

	switch content.Format {
	case FormatPlain:
		plain = appendSignature(plain, signature.Plain)
	case FormatPlainAndHTML:
		plain = appendSignature(plain, signature.Plain)

		signedHTML, signatureWarnings, err := sanitizeHTML(signature.HTML)
		if err != nil {
			return "", "", nil, err
		}

		if strings.TrimSpace(signedHTML) == "" {
			return "", "", nil, validationError("HTML signature contains no permitted content")
		}
		htmlText = appendSignature(htmlText, signedHTML)

		warnings = append(warnings, signatureWarnings...)
	case FormatHTML:
		signedHTML, signatureWarnings, err := sanitizeHTML(signature.HTML)
		if err != nil {
			return "", "", nil, err
		}

		if strings.TrimSpace(signedHTML) == "" {
			return "", "", nil, validationError("HTML signature contains no permitted content")
		}

		plainSignature := signature.Plain
		if strings.TrimSpace(plainSignature) == "" {
			plainSignature = htmlToText(signedHTML)
		}
		plain = appendSignature(strings.TrimRight(plain, "\r\n"), plainSignature)
		htmlText = appendSignature(htmlText, signedHTML)

		warnings = append(warnings, signatureWarnings...)
	case FormatPlainWithHTML:
		plain = appendSignature(plain, signature.Plain)
		htmlText = plainToHTML(plain)
	}

	return plain, htmlText, uniqueWarnings(warnings), nil
}

// Render returns the exact plain and HTML bodies that Compose would embed. It is
// for review and stable semantic digests before a caller creates a message.
func Render(content Content, signature Signature, include bool) (plain, htmlText string, warnings []string, err error) {
	return renderContent(content, signature, include)
}

func validateAttachments(attachments []Attachment, limits Limits) ([]attachmentInput, error) {
	if len(attachments) > limits.MaxAttachments {
		return nil, validationError("message has %d attachments, limit is %d", len(attachments), limits.MaxAttachments)
	}

	out := make([]attachmentInput, 0, len(attachments))
	estimatedSize := maxMIMEOverheadBytes

	for _, attachment := range attachments {
		name := strings.TrimSpace(attachment.Filename)
		if name == "" {
			return nil, validationError("attachment filename is required")
		}

		if err := rejectHeaderValue(name, "attachment filename"); err != nil {
			return nil, err
		}

		if len(name) > maxFilenameBytes {
			return nil, validationError("attachment filename is %d bytes, limit is %d", len(name), maxFilenameBytes)
		}

		contentType := strings.TrimSpace(attachment.ContentType)
		if contentType == "" {
			return nil, validationError("content type is required for %s", name)
		}

		if err := rejectHeaderValue(contentType, "attachment content type"); err != nil {
			return nil, err
		}

		if len(contentType) > maxContentTypeBytes {
			return nil, validationError("attachment content type is %d bytes, limit is %d", len(contentType), maxContentTypeBytes)
		}

		if _, _, err := mime.ParseMediaType(contentType); err != nil {
			return nil, fmt.Errorf("invalid content type for %s: %w", name, err)
		}

		if len(attachment.Data) == 0 {
			return nil, validationError("attachment %s is empty", name)
		}

		if len(attachment.Data) > limits.MaxAttachmentBytes {
			return nil, validationError("attachment %s is %d bytes, limit is %d", name, len(attachment.Data), limits.MaxAttachmentBytes)
		}

		summary := AttachmentSummary{Filename: name, ContentType: contentType, Size: len(attachment.Data)}

		encodedSize := estimatedAttachmentSize(summary, attachment.Data)
		if encodedSize > limits.MaxMessageBytes-estimatedSize {
			return nil, validationError("attachments exceed the estimated message size limit")
		}

		estimatedSize += encodedSize

		out = append(out, attachmentInput{summary: summary, data: attachment.Data})
	}

	return out, nil
}

func generatedMessageID(
	date time.Time,
	from Address,
	to, cc, bcc []Address,
	subject string,
	content Content,
	signature Signature,
	reply ReplySummary,
	attachments []attachmentInput,
) string {
	hash := sha256.New()
	writeHashField(hash, date.Format(time.RFC3339Nano), from.Name, from.Email, subject, string(content.Format), content.Plain, content.HTML, signature.Plain, signature.HTML, reply.InReplyTo, reply.ThreadID)

	writeHashAddresses(hash, "To", to)
	writeHashAddresses(hash, "Cc", cc)
	writeHashAddresses(hash, "Bcc", bcc)

	for _, reference := range reply.References {
		writeHashField(hash, reference)
	}

	for _, attachment := range attachments {
		writeHashField(hash, attachment.summary.Filename, attachment.summary.ContentType)
		attachmentDigest := sha256.Sum256(attachment.data)
		writeHashField(hash, hex.EncodeToString(attachmentDigest[:]))
	}

	return "<" + hex.EncodeToString(hash.Sum(nil))[:24] + "@composed.invalid>"
}

func writeHashAddresses(hash interface{ Write([]byte) (int, error) }, field string, addresses []Address) {
	for _, address := range addresses {
		writeHashField(hash, field, address.Name, address.Email)
	}
}

func writeHashField(hash interface{ Write([]byte) (int, error) }, fields ...string) {
	for _, field := range fields {
		_, _ = fmt.Fprintf(hash, "%d:%s\n", len(field), field)
	}
}

func rejectHeaderValue(value, field string) error {
	if strings.ContainsAny(value, "\r\n\x00") {
		return validationError("%s contains a line break or NUL", field)
	}

	return nil
}

func requireContent(value, label string) error {
	if strings.TrimSpace(value) == "" {
		return validationError("%s content is required", label)
	}

	return nil
}

func normalizeCRLF(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	value = strings.ReplaceAll(value, "\r", "\n")

	return strings.ReplaceAll(value, "\n", "\r\n")
}

func plainToHTML(value string) string {
	paragraphs := strings.Split(strings.ReplaceAll(value, "\r\n", "\n"), "\n\n")

	parts := make([]string, 0, len(paragraphs))
	for _, paragraph := range paragraphs {
		if strings.TrimSpace(paragraph) == "" {
			continue
		}
		escaped := html.EscapeString(paragraph)
		parts = append(parts, "<p>"+strings.ReplaceAll(escaped, "\n", "<br>")+"</p>")
	}

	return strings.Join(parts, "\n")
}

func appendSignature(body, signature string) string {
	return strings.TrimRight(body, "\r\n") + "\r\n\r\n" + strings.TrimLeft(signature, "\r\n")
}

func uniqueWarnings(warnings []string) []string {
	seen := make(map[string]struct{}, len(warnings))

	out := make([]string, 0, len(warnings))
	for _, warning := range warnings {
		if _, exists := seen[warning]; exists {
			continue
		}
		seen[warning] = struct{}{}
		out = append(out, warning)
	}

	return out
}

func boundedPreview(plain, htmlText string) ContentPreview {
	plainPreview, plainTruncated := boundedUTF8(plain, maxPreviewBytes)
	htmlPreview, htmlTruncated := boundedUTF8(htmlText, maxPreviewBytes)

	return ContentPreview{
		Plain:          plainPreview,
		HTML:           htmlPreview,
		PlainTruncated: plainTruncated,
		HTMLTruncated:  htmlTruncated,
	}
}

func boundedUTF8(value string, limit int) (string, bool) {
	if len(value) <= limit {
		return value, false
	}

	cut := limit
	for cut > 0 && !utf8.ValidString(value[:cut]) {
		cut--
	}

	return value[:cut], true
}

// estimatedAttachmentSize includes the exact base64 representation, the 76-byte
// line wrapping used by writeAttachment, and a conservative MIME header size.
func estimatedAttachmentSize(summary AttachmentSummary, data []byte) int {
	encoded := base64.StdEncoding.EncodedLen(len(data))
	lines := (encoded + base64LineWidth - 1) / base64LineWidth
	disposition := mime.FormatMediaType("attachment", map[string]string{"filename": summary.Filename})
	headers := len("Content-Type: ") + len(summary.ContentType) +
		len("Content-Transfer-Encoding: base64") +
		len("Content-Disposition: ") + len(disposition)

	return encoded + 2*lines + 2 + 2 + maxBoundaryBytes + 2 + headers + 6
}

func safeURL(value string) bool {
	if strings.ContainsAny(value, "\r\n\x00") {
		return false
	}

	parsed, err := url.Parse(value)
	if err != nil || parsed == nil {
		return false
	}

	if parsed.Scheme == "" {
		return false
	}

	switch strings.ToLower(parsed.Scheme) {
	case "http", "https", "mailto", "tel":
		return true
	default:
		return false
	}
}

func writeTextPart(buffer *strings.Builder, boundary, contentType, body string) {
	_, _ = fmt.Fprintf(buffer, "--%s\r\nContent-Type: %s; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n", boundary, contentType)
	writer := quotedprintable.NewWriter(buffer)
	_, _ = writer.Write([]byte(body))
	_ = writer.Close()

	buffer.WriteString("\r\n")
}

func writeAttachment(buffer *strings.Builder, boundary string, summary AttachmentSummary, data []byte) error {
	disposition := mime.FormatMediaType("attachment", map[string]string{"filename": summary.Filename})
	if disposition == "" {
		return validationError("invalid attachment filename %q", summary.Filename)
	}

	_, _ = fmt.Fprintf(buffer, "\r\n--%s\r\nContent-Type: %s\r\nContent-Transfer-Encoding: base64\r\nContent-Disposition: %s\r\n\r\n", boundary, summary.ContentType, disposition)

	encoded := base64.StdEncoding.EncodeToString(data)
	for len(encoded) > 76 {
		buffer.WriteString(encoded[:76] + "\r\n")
		encoded = encoded[76:]
	}

	if encoded != "" {
		buffer.WriteString(encoded + "\r\n")
	}

	return nil
}
